# Generated by Django 5.1.1 on 2024-11-10 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_rename_organ_to_donate_recipient_organ_needed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donors',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='date_of_birth',
        ),
    ]
