# Generated by Django 5.1.1 on 2024-11-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_remove_donors_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recipient',
            new_name='recipients',
        ),
    ]
