# Generated by Django 5.1.1 on 2024-11-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_rename_recipient_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='recipients',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
