# Generated by Django 5.1.1 on 2024-11-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_donors_date_of_birth_recipients_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='donors',
        ),
    ]
