# Generated by Django 5.1.1 on 2024-11-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_delete_donors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='recipients',
        ),
    ]
