# Generated by Django 5.1.1 on 2024-11-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
